graph TD
    PoBabyTouchGc.Shared --> PoBabyTouchGc.Client
    PoBabyTouchGc.Shared --> PoBabyTouchGc.Server
    PoBabyTouchGc.Client --> PoBabyTouchGc.Server
    PoBabyTouchGc.Server --> PoBabyTouchGc.IntegrationTests
