name: Deploy to Azure with GH and Azure CLI

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  deployments: write # Write permission for deployments
  statuses: write    # Write permission for deployment statuses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y
        gh --version
    
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version
        
    - name: Restore dependencies
      run: dotnet restore PoBabyTouchGc.sln
      
    - name: Build
      run: dotnet build PoBabyTouchGc.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test PoBabyTouchGc.sln --configuration Release --no-build
      
    - name: Publish
      run: dotnet publish Server/PoBabyTouchGc.Server/PoBabyTouchGc.Server.csproj -c Release -o ${{github.workspace}}/publish
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App with Azure CLI
      id: deploy-to-azure
      run: |
        echo "Starting deployment to Azure Web App using Azure CLI..."
        # Create a zip file of the published output
        cd ${{github.workspace}}/publish
        zip -r site.zip ./*
        
        # Validate webapp exists before deployment
        echo "Validating Azure Web App..."
        az webapp show --resource-group PoBabyTouch --name PoBabyTouchApp --query name
        
        # Deploy the zip file to Azure Web App
        echo "Deploying to Azure App Service..."
        RESULT=$(az webapp deployment source config-zip \
          --resource-group PoBabyTouch \
          --name PoBabyTouchApp \
          --src site.zip)
          
        echo "Deployment completed with result: $RESULT"
        
        if [ $? -eq 0 ]; then
          echo "DEPLOY_SUCCESS=true" >> $GITHUB_ENV
          # Get app details for verification
          echo "Getting app details for verification..."
          APP_URL=$(az webapp show --resource-group PoBabyTouch --name PoBabyTouchApp --query defaultHostName -o tsv)
          echo "APP_URL=https://$APP_URL" >> $GITHUB_ENV
          
          # Restart the webapp to apply changes
          echo "Restarting the web app to apply changes..."
          az webapp restart --resource-group PoBabyTouch --name PoBabyTouchApp
        else
          echo "DEPLOY_SUCCESS=false" >> $GITHUB_ENV
        fi
                
    - name: Create GitHub deployment status
      if: always()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating GitHub deployment..."
        if [ "${{ env.DEPLOY_SUCCESS }}" == "true" ]; then
          # Create a deployment and set status to success in one step
          gh api \
            repos/${{ github.repository }}/deployments \
            --field ref="${{ github.ref }}" \
            --field environment="production" \
            --field description="Deployment to Azure App Service" \
            --field auto_merge=false \
            --raw-field required_contexts=[]
          
          echo "Setting GitHub status to success"
          gh api \
            repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -F state="success" \
            -F target_url="${{ env.APP_URL }}" \
            -F description="Deployment to Azure App Service completed successfully!" \
            -F context="Azure App Service deployment"
        else
          echo "Setting GitHub status to failure"
          gh api \
            repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -F state="failure" \
            -F description="Deployment to Azure App Service failed." \
            -F context="Azure App Service deployment"
        fi
        
    - name: Verify deployment with Azure CLI
      if: env.DEPLOY_SUCCESS == 'true'
      run: |
        echo "Verifying deployment status..."
        SITE_URL="${{ env.APP_URL }}"
        
        # Add retry logic with exponential backoff
        max_retries=5
        retry_count=0
        wait_time=10
        
        while [ $retry_count -lt $max_retries ]; do
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $SITE_URL)
          
          if [ $HTTP_STATUS -eq 200 ] || [ $HTTP_STATUS -eq 302 ]; then
            echo "✅ Deployment verification successful: Site is responding with HTTP status $HTTP_STATUS"
            break
          else
            retry_count=$((retry_count+1))
            if [ $retry_count -lt $max_retries ]; then
              echo "⚠️ Site is responding with HTTP status $HTTP_STATUS. Retrying in $wait_time seconds... (Attempt $retry_count/$max_retries)"
              sleep $wait_time
              wait_time=$((wait_time*2)) # Exponential backoff
            else
              echo "❌ Deployment verification failed after $max_retries attempts: Site is responding with HTTP status $HTTP_STATUS"
              echo "You can manually check the site at $SITE_URL"
              
              # Mark GitHub deployment as inactive
              gh api \
                repos/${{ github.repository }}/statuses/${{ github.sha }} \
                -F state="error" \
                -F target_url="${{ env.APP_URL }}" \
                -F description="Deployment completed but site verification failed." \
                -F context="Azure App Service deployment"
            fi
          fi
        done
