# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - PoBabyTouch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Clean before publish
        run: dotnet clean --configuration Release

      - name: dotnet publish
        run: dotnet publish Server/PoBabyTouchGc.Server/PoBabyTouchGc.Server.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9C9AD85F722F452C84272F18C534A51F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_74EE0A2986C64551BDB103FA94B3FC64 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF244B77D8B0479E9764FCD6FBDE25B1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PoBabyTouch'
          slot-name: 'Production'
          package: .
          
      - name: Configure Azure Table Storage Connection String
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name PoBabyTouch --resource-group pobabytouch --settings "ConnectionStrings:AzureTableStorage=DefaultEndpointsProtocol=https;AccountName=posharedtablestorage;AccountKey=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }};EndpointSuffix=core.windows.net"
          